//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp8.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public string idLichChieu { get; set; }
        public string idPhim { get; set; }
        public Nullable<double> Tien { get; set; }
    
        public virtual LichChieu LichChieu { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
