//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp8.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.DoanhThus = new HashSet<DoanhThu>();
        }
    
        public string id { get; set; }
        public System.DateTime ThoiGianChieu { get; set; }
        public string idPhong { get; set; }
        public string idDinhDang { get; set; }
        public decimal GiaVe { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DinhDangPhim DinhDangPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanhThu> DoanhThus { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
    }
}
