//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp8.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongChieu()
        {
            this.LichChieux = new HashSet<LichChieu>();
        }
    
        public string id { get; set; }
        public string TenPhong { get; set; }
        public string idManHinh { get; set; }
        public int SoChoNgoi { get; set; }
        public int TinhTrang { get; set; }
        public int SoHangGhe { get; set; }
        public int SoGheMotHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieu> LichChieux { get; set; }
        public virtual LoaiManHinh LoaiManHinh { get; set; }
    }
}
